all: 01 02 03 04 05 06

01:
	gcc 01_declaracao_ponteiro.c -o 01_declaracao_ponteiro

02:
	gcc 02_atribuicao_por_ponteiro.c -o 02_atribuicao_por_ponteiro

03:
	gcc 03_erro_ponteiro_nao_inicializado.c -o 03_erro_ponteiro_nao_inicializado

04:
	gcc 04_troca_incorreta.c -o 04_troca_incorreta

05:
	gcc 05_troca_correta.c -o 05_troca_correta

06:
	gcc 06_recursividade_exemplo.c -o 06_recursividade_exemplo

clean:
	rm -f 01_* 02_* 03_* 04_* 05_* 06_*
